### ISSUE TITLE
主题问题

### ISSUE THREAD

**Issue by ErShuoZi** [sunhao1256/lulu-admin#2]
大佬，定义好了主题之后，我怎么样才能知道这些颜色默认作用于那些组件上呢？一头雾水

**Comment by sunhao1256** [comment]
没明白，选中主题后会应用到所有默认组件上，可以看css变量是否生效

**Comment by sunhao1256** [comment]
> 大佬，定义好了主题之后，我怎么样才能知道这些颜色默认作用于那些组件上呢？一头雾水

没听明白，选中主题后会应用到所有默认组件上，可以看下默认组件的源码
